// IMPORT PROGRAM
// ═══════════════════════════════════════════════════
function showImportUI(){
  const ov=makeOv('import-ov');
  ov.innerHTML=`<div class="modal" style="max-height:92vh"><div class="mh"></div><div class="mt">Import Program</div>
    <div style="font-size:12px;color:var(--muted);margin-bottom:10px;line-height:1.5">Paste the JSON generated by an LLM (ChatGPT, Claude, etc.) using the Lah We import SOP. It will create routines and optionally a group.</div>
    <textarea id="import-json" class="import-ta" placeholder='Paste JSON here…'></textarea>
    <div id="import-preview-area"></div>
    <div style="display:flex;gap:8px;margin-top:10px">
      <button class="btn btp bfw" id="import-go-btn" onclick="doImport()" disabled>Import</button>
      <button class="btn btg" style="padding:11px 16px" onclick="dismissOv(document.getElementById('import-ov'))">Cancel</button>
    </div>
  </div>`;
  document.body.appendChild(ov);attachSwipeDown(ov);
  document.getElementById('import-json').addEventListener('input',previewImport);
}
function previewImport(){
  const raw=document.getElementById('import-json')?.value?.trim();
  const area=document.getElementById('import-preview-area');
  const btn=document.getElementById('import-go-btn');
  if(!area)return;
  if(!raw){area.innerHTML='';if(btn)btn.disabled=true;return;}
  let d;
  try{d=JSON.parse(raw);}catch(e){area.innerHTML=`<div class="import-warn">Invalid JSON: ${esc(e.message)}</div>`;if(btn)btn.disabled=true;return;}
  try{
    const parsed=parseImport(d);
    if(parsed.error){area.innerHTML=`<div class="import-warn">${parsed.error}</div>`;if(btn)btn.disabled=true;return;}
    let html='';
    (parsed.groups||[]).forEach(g=>{
      html+=`<div class="import-row"><div class="ir-name">📁 Group: ${esc(g.name)}</div><div class="ir-meta">Mode: ${g.mode||'rotation'} · ${g.routineCount} routines</div></div>`;
    });
    parsed.routines.forEach(r=>{
      const exCount=r.exercises.length;
      const ssCount=new Set(r.exercises.filter(e=>e.link).map(e=>e.link)).size;
      const newCount=r.exercises.filter(e=>e._isNew).length;
      const matchCount=exCount-newCount;
      html+=`<div class="import-row"><div class="ir-name">${esc(r.name)}</div><div class="ir-meta">${exCount} exercises · ${matchCount} matched · ${newCount} new custom${ssCount?` · ${ssCount} superset${ssCount>1?'s':''}`:''}</div></div>`;
    });
    if(parsed.warnings.length)html+=`<div class="import-warn">${parsed.warnings.join('<br>')}</div>`;
    area.innerHTML=`<div class="import-preview">${html}</div>`;
    if(btn)btn.disabled=false;
    window._importParsed=parsed;
  }catch(e){area.innerHTML=`<div class="import-warn">Import error: ${esc(e.message)}</div>`;if(btn)btn.disabled=true;}
}
function parseImport(d){
  const warnings=[];
  // Fix #3: Support both {group, routines} and {groups: [{name, mode, routines}]}
  let groupDefs=[];let allRoutines=[];
  if(d.groups&&Array.isArray(d.groups)){
    d.groups.forEach(g=>{
      const rStart=allRoutines.length;
      const rtns=(g.routines||[]).map(r=>parseRoutine(r,warnings));
      allRoutines.push(...rtns);
      groupDefs.push({name:g.name||'Imported Group',mode:g.mode||'rotation',routineCount:rtns.length,_start:rStart,_count:rtns.length});
    });
  }else if(d.routines&&Array.isArray(d.routines)){
    allRoutines=d.routines.map(r=>parseRoutine(r,warnings));
    if(d.group)groupDefs.push({name:d.group.name||'Imported Group',mode:d.group.mode||'rotation',routineCount:allRoutines.length,_start:0,_count:allRoutines.length});
  }else{return{error:'JSON must have "routines" or "groups" array.'};}
  if(!allRoutines.length)return{error:'No routines found.'};
  return{routines:allRoutines,groups:groupDefs,warnings};
}
function parseRoutine(r,warnings){
  if(!r.name)r.name='Imported Routine';
  const exercises=(r.exercises||[]).map(e=>{
    const matched=matchExercise(e.name||e.id||'');
    let exId;let isNew=false;
    if(matched){exId=matched.id;}
    else{
      exId=`custom-${uid()}`;isNew=true;
      const cat=guessCat(e.name||'');const eq=guessEq(e.equipment||e.eq||'');const muscle=e.muscle||guessMuscle(cat);
      if(!S.custom)S.custom=[];
      const secs=(e.secondaryMuscles||[]).filter(m=>MEV_MAV[m]&&m!==muscle);
      S.custom.push({id:exId,name:e.name||'Unknown',cat,eq,muscle,sec:secs});
      if(secs.length)SEC_MUSCLE[exId]=secs;
      warnings.push(`"${esc(e.name||'?')}" → new custom`);
    }
    return{exId,sets:parseInt(e.sets)||3,w:e.weight||'',r:String(e.reps||''),type:e.type||'flat',rest:e.rest!=null?parseInt(e.rest):null,link:e.link||null,_isNew:isNew};
  });
  return{name:r.name,notes:r.notes||'',exercises};
}
// Fix #2: Score-based matching, no greedy contains
function matchExercise(name){
  if(!name)return null;
  const lower=name.toLowerCase().trim();
  const all=allEx();
  // 1. Exact name match
  let m=all.find(e=>e.name.toLowerCase()===lower);if(m)return m;
  // 2. Exact id match
  m=all.find(e=>e.id===lower);if(m)return m;
  // 3. Score-based: tokenize, compute overlap ratio, require high precision
  const stops=new Set(['the','and','with','for','set','on','of','to','in','a','w']);
  const inToks=lower.split(/[\s\-_\/\(\)]+/).filter(t=>t.length>1&&!stops.has(t));
  if(!inToks.length)return null;
  let best=null,bestScore=0;
  all.forEach(e=>{
    const eToks=e.name.toLowerCase().split(/[\s\-_\/\(\)]+/).filter(t=>t.length>1&&!stops.has(t));
    if(!eToks.length)return;
    // How many catalog tokens appear in input (forward match)
    const fwd=eToks.filter(ct=>inToks.some(it=>it===ct)).length;
    const fwdRatio=fwd/eToks.length;
    // Length similarity bonus
    const lenRatio=Math.min(inToks.length,eToks.length)/Math.max(inToks.length,eToks.length);
    // Require ALL catalog tokens present in input
    if(fwdRatio<1)return;
    // Score favors similar-length names (penalizes "Leg Curl" matching "Seated Leg Curl")
    const score=fwdRatio*0.6+lenRatio*0.4;
    if(score>bestScore){bestScore=score;best=e;}
  });
  // Require length ratio ≥ 0.5 to avoid "Leg Curl" matching "Seated Lying Leg Curl Machine"
  if(best&&bestScore>=0.9)return best;
  return null;
}
function guessCat(name){
  const n=name.toLowerCase();
  if(/bench|chest|fly|push.?up|pec/i.test(n))return'Chest';
  if(/row|pull|lat|back|deadlift/i.test(n))return'Back';
  if(/shoulder|press|lateral|ohp|delt|raise/i.test(n))return'Shoulders';
  if(/curl|bicep/i.test(n))return'Biceps';
  if(/tricep|skull|pushdown|extension/i.test(n))return'Triceps';
  if(/squat|leg|lunge|calf|ham|glute|rdl|hip/i.test(n))return'Legs';
  if(/crunch|plank|ab|core|russian|sit.?up/i.test(n))return'Core';
  return'Full Body';
}
function guessEq(eq){
  const map={'barbell':'Barbell','dumbbell':'Dumbbell','db':'Dumbbell','cable':'Cable','machine':'Machine','bodyweight':'Bodyweight','bw':'Bodyweight','kettlebell':'Kettlebell','kb':'Kettlebell','band':'Other','smith':'Machine'};
  return map[(eq||'').toLowerCase()]||'Other';
}
function guessMuscle(cat){
  const map={'Chest':'Chest','Back':'Lats','Shoulders':'Shoulders','Biceps':'Biceps','Triceps':'Triceps','Legs':'Quads','Core':'Abs','Full Body':'Quads'};
  return map[cat]||'Quads';
}
// Fix #3: doImport supports multi-group
function doImport(){
  const parsed=window._importParsed;if(!parsed)return;
  if(!S.routines)S.routines=[];if(!S.groups)S.groups=[];
  const allRids=[];
  parsed.routines.forEach(r=>{
    const rid=uid();
    // Strip _isNew flags before storing
    const cleanEx=r.exercises.map(e=>{const c={...e};delete c._isNew;return c;});
    S.routines.push({id:rid,name:r.name,notes:r.notes,exercises:cleanEx,days:[]});
    allRids.push(rid);
  });
  parsed.groups.forEach(g=>{
    const gid=uid();
    const routineIds=allRids.slice(g._start,g._start+g._count);
    S.groups.push({id:gid,name:g.name,mode:g.mode,routineIds,cursor:0,dayMap:{},daysPerWeek:routineIds.length,active:!getActiveGroup()});
  });
  save();
  dismissOv(document.getElementById('import-ov'));
  const gCount=parsed.groups.length;
  const msg=`Imported ${parsed.routines.length} routine${parsed.routines.length>1?'s':''}${gCount?` + ${gCount} group${gCount>1?'s':''}`:''}`; 
  toast(msg,'green');
  S.libTab='routines';renderLibrary(document.getElementById('content'));
}

// ═══════════════════════════════════════════════════
